config/routes.rb
Blog::Application.routes.draw do
  resources :comments

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'user_sessions#destroy', :as => :logout

  match 'login' => 'user_sessions#new', :as => :login

  resources :user_sessions

  resources :users

  resources :products

  resources :posts do
    resources :comments
  end

  get "home/index"
  get "home/about"

   root :to => 'home#index'

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Blog
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "#"} Project CV
          .nav-collapse
            %ul.nav
              %li.active
                %a{:href => "#"} Home
              %li
                = link_to "Blog", posts_path
              %li
                = link_to "Products", products_path
              %li
                = link_to "About", "home/about"
              %li
                %a{:href => "#contact"} Contact
            %ul.nav.pull-right
              - if current_user
                %li
                  = link_to "Edit Profile", edit_current_user_path
                %li
                  = link_to "Logout", logout_path
              - else
                %li
                  = link_to "Register", signup_path
                %li
                  = link_to "Login", login_path
    .container
      = yield